/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kredinEgemenden;

import com.kredinEgemenden.enums.LoanType;
import com.kredinEgemenden.enums.SectorType;
import com.kredinEgemenden.model.Application;
import com.kredinEgemenden.model.Bank;
import com.kredinEgemenden.model.Campaign;
import com.kredinEgemenden.model.CreditCard;
import com.kredinEgemenden.model.User;
import com.kredinEgemenden.model.factories.UserHandler;
import com.kredinEgemenden.model.factories.ApplicationHandler;
import com.kredinEgemenden.model.factories.BankFactory;
import com.kredinEgemenden.model.factories.CampaignFactory;
import com.kredinEgemenden.model.factories.CreditCardFactory;
import com.kredinEgemenden.model.factories.LoanFactory;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {
        
        Bank akBank = BankFactory.createBank("AkBank");
        CreditCardFactory ccFactory = CreditCardFactory.getInstance();
        
        CreditCard redCard = akBank.getCreditCardsFactory()
                                    .createCreditCard("Red Banka karti", BigDecimal.ONE, akBank);
        CreditCard sariCard = ccFactory.createCreditCard("Sari Kart", BigDecimal.TEN, akBank);
        CreditCard yeyoCard = akBank.newCreditCard("YeYo_Card", BigDecimal.TEN);
        
        
        LoanFactory loanFactory = LoanFactory.getInstance();

        loanFactory.createLoan("Ilk Evim Konut Kredisi", LoanType.HOUSE_LOAN, BigDecimal.valueOf(500000), 120,  BigDecimal.valueOf(2.90), akBank);
        loanFactory.createLoan("Direkt Kredi", LoanType.CONSUMER_LOAN, BigDecimal.valueOf(50000), 12,  BigDecimal.valueOf(4.60), akBank);            

        
        List<Campaign> campaignList = new ArrayList<>();
        campaignList.add(CampaignFactory.createCampaign("Yeyokampanyasi",
                                                "GüzelbirKampanya",
                                                LocalDate.now(),
                                                LocalDate.now(), 
                                                LocalDate.now(), 
                                                SectorType.MARKET));
        
        yeyoCard.setCampaignList(campaignList);
        
        
        Campaign campaign1 = CampaignFactory.createCampaign("AAAcampanyasi",
                "FasoFiso",
                LocalDate.MAX,
                LocalDate.MAX,
                LocalDate.MAX,
                SectorType.MARKET);
        Campaign campaign2 = CampaignFactory.createCampaign("BBBcampanyasi",
                "YEy0HeHo",
                LocalDate.MAX,
                LocalDate.MAX,
                LocalDate.MAX,
                SectorType.MARKET);
        yeyoCard.addCampaign(campaign2);
        yeyoCard.addCampaign(campaign1);
        redCard.addCampaign(campaign2);
        sariCard.addCampaign(campaign1);
        CreditCardFactory.addCampaignToCreditCard(campaign1, redCard);
        redCard.addCampaign(campaign1); //Same campaigns can't be added to creditCards


        System.out.println("\n\n########################################################################");
        System.out.println("\tAyni e-mail adresi ile bir kullanici kayit olabilir.");
        System.out.println("########################################################################");
        UserHandler userHandler = UserHandler.getInstance();
        User user1 = userHandler.newUser("Egemen@gmail.com", "YeYo", "Egemen", "Ulcm", LocalDate.now(), "55544433312");
        System.out.println("user1: \n" + user1);
        User user2 = UserHandler.newUser("Baska@gmail.com", "YoYe", "Baskasi", "Ulcm", LocalDate.now(), "55544433312");
        System.out.println("user2: \n" + user2);
        
        System.out.println("user3 with user1's email address");
        User user3 = UserHandler.newUser("Egemen@gmail.com", "YeY0", "Egemen_2", "Ulcm", LocalDate.now(), "55544433312");
        System.out.println("user3: \n" + user3);
        System.out.println("user1 == user3 :" + (user1 == user3));
        
        System.out.println("\n\n########################################################################");
        System.out.println("\tSHA-512 ile sifreleme");
        System.out.println("########################################################################");
        System.out.println(user3);
        //System.out.println("USER LIST Len: " + UserHandler.getUserList().size());
        //System.out.println(UserHandler.getUserList());
        
        

        
        System.out.println("\n\n########################################################################");
        System.out.println("\tEn cok basvuru yapan kullanici");
        System.out.println("########################################################################");
        
        user1.makeApplication(yeyoCard);
        user1.makeApplication(redCard);
        Application consumerLoanApplication = user1.makeApplication(akBank.findLoanByName(LoanType.CONSUMER_LOAN, "Direkt Kredi"));
        consumerLoanApplication.setApplicationDate(LocalDateTime.now().minusMonths(2));

        
        user2.makeApplication(akBank.findLoanByName(LoanType.HOUSE_LOAN, "Ilk Evim Konut Kredisi"));
        //user2.makeApplication(akBank.findLoanByName(LoanType.CONSUMER_LOAN, "Direkt Kredi"));
        //user2.makeApplication(sariCard);
        //System.out.println(user1);
        //System.out.println(user2);
        System.out.println(UserHandler.getUserWithMostApplications());
        
        
        System.out.println("\n\n########################################################################");
        System.out.println("\tEn yuksek kredi isteyen kullaniciyi ve istedigi tutari");
        System.out.println("########################################################################");
        
        System.out.println("MOST AMOUNT APPLICATION: ");
        Application applicationMostAmount = ApplicationHandler.getLoanApplicationWithMostAmount();
        System.out.println(applicationMostAmount);
        
        System.out.println("The User : ");
        //System.out.println(applicationMostAmount.getUser());    // Also can be pulled from Application
        System.out.println(UserHandler.getUserWithMostAmountLoanApplication());
        
        
        
        
        System.out.println("\n\n########################################################################");
        System.out.println("\tSon X aylik yapilan basvuru");
        System.out.println("########################################################################");
        System.out.println("Last 1 months applications: ");
        System.out.println(ApplicationHandler.getApplicationsForLastMonths(1));
        System.out.println("Last 3 months applications: ");
        System.out.println(ApplicationHandler.getApplicationsForLastMonths(3));
        
        
        
        
        System.out.println("\n\n########################################################################");
        System.out.println("Kampanya sayisi en coktan aza dogru olacak sekilde kredi karti tekliflerini listeleyen methodu yazin");
        System.out.println("########################################################################");
        //System.out.println("CreditCardList:");
        //System.out.println(CreditCardFactory.creditCardList);
        System.out.println("SortedCreditCardListByCampaignDescending: ");
        System.out.println(CreditCardFactory.getSortedCreditCardListByCampaignDescending());
        
        
        
        
        System.out.println("\n\n########################################################################");
        System.out.println("X mail adresine sahip kullanicinin butun basvurulari");
        System.out.println("########################################################################");
        System.out.println("##----    Email: Egemen@gmail.com    ----## ");
        System.out.println(ApplicationHandler.getApplicationsOfTheUserByEmail("Egemen@gmail.com"));
        System.out.println("##----    Email: Baska@gmail.com    ----## ");
        System.out.println(ApplicationHandler.getApplicationsOfTheUserByEmail("Baska@gmail.com"));
    }
}
